### ISSUE TITLE
Broken links in "Recent posts"

### ISSUE THREAD

**Issue by joelso** [lwolf/lwolf.github.io#1]
Great blog! Just found it via kube.news.

Noticed that links in "Recent posts" and possibly other places are broken.

It tries to navigate to this http://blog.lwolf.org/post/going-open-source-in-monitoring-part-i-deploying-prometheus-and-grafana-to-kubernetes/ 

...but after checking this repo I think it should be http://blog.lwolf.org/post/going-open-source-in-monitoring-part-I-deploying-prometheus-and-grafana-to-kubernetes/

**Comment by lwolf** [comment]
Hi, thank you very much for letting me know

**Comment by lwolf** [comment]
should be fixed now, thanks again
